import {
  getPopularMovies,
  getPopularTVShows,
  getTrendingMovies,
  getTrendingTVShows,
  getUpcomingMovies,
  getAiringTodayTVShows,
  getTopRatedMovies,
  getTopRatedTVShows,
  getPopularMoviesByLanguage,
  getPopularTVShowsByLanguage,
  searchMovies,
  searchTVShows,
  getMoviesByGenre,
  getMovieDetails,
  getMoviesByActor,
} from "./routes";

export {
  getPopularMovies,
  getPopularTVShows,
  getTrendingMovies,
  getTrendingTVShows,
  getUpcomingMovies,
  getAiringTodayTVShows,
  getTopRatedMovies,
  getTopRatedTVShows,
  getPopularMoviesByLanguage,
  getPopularTVShowsByLanguage,
  searchMovies,
  searchTVShows,
  getMoviesByGenre,
  getMovieDetails,
  getMoviesByActor,
};
